In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [ ]:
coin_flips = np.random.randint(0,2,10000)

In [ ]:
coin_flips[:10]

array([1, 0, 0, 1, 0, 1, 1, 0, 1, 0])

In [ ]:
coin_flips.mean()

0.5085

In [ ]:
dice_rolls = np.random.randint(0,4,10000) +1

In [ ]:
dice_rolls[:10]

array([1, 2, 4, 4, 4, 3, 2, 3, 2, 3])

In [ ]:
num_ones = len(dice_rolls[dice_rolls == 1])
num_ones

2513

In [ ]:
num_ones = (dice_rolls == 1).sum()
num_ones

2513

In [ ]:
roll_counts = np.array([(dice_rolls == roll).sum()
                           for roll in range (1,5)])
roll_counts

array([2513, 2488, 2562, 2437])

In [ ]:
roll_counts.mean()

2500.0

In [ ]:
dice_rolls.mean()

2.4923

In [ ]:
(1*roll_counts[0] + 2*roll_counts[1] + 3*roll_counts[2] + 4*roll_counts[3])/len(dice_rolls)

2.4923

In [ ]:
roll_mean = 0
for index, count in enumerate(roll_counts):
  roll_mean += (index+1)*count

roll_mean/len(dice_rolls)

2.4923