In [2]:
import math

In [3]:
x=10**5

In [4]:
math.log10(x)

5.0

In [6]:
some_numbers=list(range(1,10**7))

In [9]:
log_numbers = []
for num in some_numbers:
  log_number.append(math.log10(num))

In [10]:
log_numbers = for num in some_numbers:
  log_numbers.append(math.log10(num))

SyntaxError: ignored

In [11]:
import numpy as np

In [12]:
n_numbers = np.arange(1,10**8)

In [13]:
n_log_numbers = np.log10(n_numbers)

In [14]:
a = np.array([3,4,8,16])

In [15]:
a

array([ 3,  4,  8, 16])

In [16]:
a.shape

(4,)

In [17]:
b = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])

In [18]:
b.shape

(3, 3)

In [19]:
len(a)

4

In [20]:
len(b)

3

In [21]:
c = np.array([
    [[1]],
    [[2]],
    [[3]]
])

In [22]:
c.shape

(3, 1, 1)

In [23]:
a

array([ 3,  4,  8, 16])

In [26]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[2]

2

In [28]:
a[-1]

9

In [29]:
a[1:5]

array([1, 2, 3, 4])

In [30]:
a[0: -1: 4]

array([0, 4, 8])

In [32]:
mat = np.array([10,9,8,7,6,5,4])

submat=mat[-3:]
print(mat,submat)

[10  9  8  7  6  5  4] [6 5 4]


In [33]:
submat [:] = 12
print(submat)

[12 12 12]


In [34]:
print(mat)

[10  9  8  7 12 12 12]


In [35]:
submat2=np.array(mat[0:5])

In [37]:
submat2

array([10,  9,  8,  7, 12])

In [38]:
submat2[:]=44

In [39]:
mat

array([10,  9,  8,  7, 12, 12, 12])

In [40]:
submat2

array([44, 44, 44, 44, 44])

In [41]:
mat >= 10

array([ True, False, False, False,  True,  True,  True])

In [42]:
mat[mat >= 10]

array([10, 12, 12, 12])

In [43]:
mat[(mat>=10)&(mat<12)]

array([10])

In [44]:
np.ones((10,11))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
np.zeros((10,11))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
mat * 14

array([140, 126, 112,  98, 168, 168, 168])

In [47]:
mat + 1

array([11, 10,  9,  8, 13, 13, 13])

In [49]:
mat.sum()

70

In [50]:
mat.mean()

10.0

In [51]:
mat.max()

12

In [52]:
d = list(mat)

In [53]:
type(d)

list